### ISSUE TITLE
Question： how to hide stepback and reverse button on debug toolbar？

### ISSUE THREAD

**Issue by longwind91** [microsoft/vscode-mock-debug#107]
I don't need  stepback and reverse button，how to hide these buttons？Dose anyone know how to do that? Thank you very much!

![image](https://github.com/microsoft/vscode-mock-debug/assets/39149208/b1720183-1ceb-4556-83b7-5f58a773fb34)

**Comment by Shoko-Bo** [comment]
in the function 'initializeRequest()'

set:

		response.body.supportsStepBack = false

to false

**Comment by longwind91** [comment]
> in the function 'initializeRequest()'
> 
> set:
> 
> ```
> 	response.body.supportsStepBack = false
> ```
> 
> to false

thank you very much！ It works
