### ISSUE TITLE
append some thing to the outputchanel

### ISSUE THREAD

**Issue by NumberX** [Microsoft/vscode-mock-debug#13]
I have create it an outputchanel in the extension.ts , i would like to append to it  some thing from the function variablerequest in the mockdebug.ts  , i dont no how to do it.

With many thanks

**Comment by weinand** [comment]
`extension.ts` runs in the extension host and `mockdebug.ts` in the debug adapter (a separate process). So you cannot directly call code from the debug adapter  in the extension.

But you can send a request via VS Code. You can find the API here: https://github.com/Microsoft/vscode/blob/7590a94eb6cc46b874126593bdfcd369a5e859b3/src/vs/vscode.d.ts#L5593
