### ISSUE TITLE
.vscodeignore containing node_modules causes problems

### ISSUE THREAD

**Issue by bxantus** [Microsoft/vscode-mock-debug#14]
I just recently found out, while packaging my debugger (it was forked from the mock-debug extension), that vsce won't package files found in the .vscodeignore file.

This may be a fine choice, but unfortunately this caused a hard to debug problem for me. After installing my extension I repeatedly got: "Debug adapter process has terminated unexpectedly" errors when trying to launch a new debug session.
After I started manually my debugger.js file, had I noticed that vsce didn't package my dependency node modules.

I suggest removing the line ignoring node_modules from the .vscodeignore file, as the same issue can happen with other developers too.
Always remembering to white-list new dependencies (and all of their dependencies!) is a tedious task in my opinion. Looks like vsce  is smart enough to package dependent node modules.

I realize that this can be solved differently (like vsce having a different ignore file etc.), but probably having an easy to use setup in the mock-debug project would help out many new debug extension developers.

**Comment by weinand** [comment]
Oh, these .vscodeignore globs were from a time where `vcse` wasn't smart enough to understand the devDependencies.

**Comment by bxantus** [comment]
thanks for the quick response and fix!
