### ISSUE TITLE
[Question] showInputBox vs. showOpenDialog

### ISSUE THREAD

**Issue by DatGuyJonathan** [microsoft/vscode-mock-debug#16]
I'm working on a debug adapter that requires a local file in the launch config. I like that the mock-debug allows the file to be specified in the launch config or prompt the user for it. I noticed the prompt uses `showInputBox` so the user would have to type/paste the file path. Is that the preferred design instead of something like `showOpenDialog`? Any downside of using `showOpenDialog`?

**Comment by weinand** [comment]
no, using showOpenDialog is fine too.
