### ISSUE TITLE
Can not Set Value in "Variables"

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-mock-debug#23]
Hello everyone,

I implemented a working version of the debug adapter based on the vscode-mock-debug.
I however couldn't set value in "Variables" even with setting supportsSetVariable = true.

I run the vscode-mock-debug with the readme.md file and found out that the mock-debug has the same problem.

Could you please help me with this problem?
Thank you.
ttran

**Comment by weinand** [comment]
Did you implement the [setVariable](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_SetVariable) request?
