### ISSUE TITLE
On trying to  debug Runtime process using 'mock' configuration, getting 'Cannot find a program to debug' as info response.

### ISSUE THREAD

**Issue by anoop-rs** [microsoft/vscode-mock-debug#24]
I am currently trying to use mock debug to build a customised debugger. On trying to use mock-debugger to debug the Runtime process ('mock' configuration for type field) , I am getting an info pop up that says 'Cannot find a program to debug'.  I am getting the same issue in the customised debugger as well. Here is my launch.json
```
{
    "version": "0.1.0",
    "configurations": [
        {
            "type": "node",
            "request": "attach",
            "name": "node attach",
            "address": "localhost",
            "port": 9222,
            "protocol": "inspector",
            "trace": true,
        },
        {
            "type": "mock",
            "request": "attach",
            "name": "Attach to Remote",
            "address": "localhost",
            "port": 9222,
            "trace": true,
            "webRoot": "${workspaceFolder}"
        }
   ]
}
```
The debugger works fine and loads the scripts on using 'node' configuration in type field.  
No traces are being generated for mock. 
Is something wrong with my approach, or is it a known issue?

**Comment by weinand** [comment]
You cannot use mock for real debugging. And it does not understand "attach" either.
