### ISSUE TITLE
Howto prevent evaluation of comments?

### ISSUE THREAD

**Issue by paulo-fernando-silva** [microsoft/vscode-mock-debug#30]
The language selected should be marking certain blocks as comments - I imagine.
Assuming that this is the case, does vsc still request evaluation of these blocks?
It seems to do so in the case of my plugin.

**Comment by weinand** [comment]
I do not understand the question.

**Comment by paulo-fernando-silva** [comment]
Thank you for taking the time to respond. The idea is that vsc will ask the
debugger to evaluate anything that the cursor hovers, even comments. Most
of the time that evolution makes no sense. Is there a way to have vsc not
evaluate things that the language marked as comments?

Thanks



-- 
Paulo Silva
Tel: (+81) 080-4158-9090
E-mail: paulo.fernando.silva@gmail.com
Web: https://sites.google.com/site/paulofernandosilva

**Comment by weinand** [comment]
Currently VS Code uses a naive heuristic (regular expression) to determine what under the mouse is evaluated to be shown in the debug hover. 

In the upcoming release of VS Code 1.43 we have added new extension API which allows language or debugger extensions to control what source under the mouse will be evaluated.
See https://github.com/microsoft/vscode/issues/89084 for details.
