### ISSUE TITLE
[Question] How can I run a server for debugger?

### ISSUE THREAD

**Issue by vanheck** [microsoft/vscode-mock-debug#32]
Hi, apologize for my "newbie" question.

I'd like to create a lua debuger extension, where the debuger (on the vscode side) is TCP Server waiting for client (lua program) to connect. But I have no idea how to connect the Debug Adapter with the "_runtime" (mockRuntime in this example)  which works as a server waiting for connection and messeges with debug info.

Could you help me? What should I focus on?

**Comment by weinand** [comment]
Yes, MockDebug assumes that the underlying runtime/debugger can be accessed via a client library.  The "mockRuntime" can be considered this client library.
If your runtime ("lua") is a TCP server, then you need a client library "luaRuntime" that talks to the lua TCP server.

I suggest that you ask for advice on stackoverflow.
