### ISSUE TITLE
Link broken in README.md

### ISSUE THREAD

**Issue by nacho4d** [Microsoft/vscode-mock-debug#4]
I realized that a link in the README is broken.

> More information about how to develop a new debug adapter can be found [here].

**Comment by weinand** [comment]
@nacho4d link works for me.

**Comment by nacho4d** [comment]
If it works for you then it means it exists but I (and other people) don't have enough access rights.

<img width="800" alt="screen shot 2016-02-01 at 23 14 04" src="https://cloud.githubusercontent.com/assets/111651/12719628/a8dafd44-c939-11e5-9ae1-c704ab27c2ca.png">

**Comment by nacho4d** [comment]
Is this repo public? https://github.com/Microsoft/vscode-extensionbuilders/

**Comment by weinand** [comment]
@nacho4d '404' or 'no access rights' are an important detail ;-) I've fixed the link. Thanks for reporting!
