### ISSUE TITLE
Improve debugEditorContents and runEditorContents command examples

### ISSUE THREAD

**Issue by gjsjohnmurray** [microsoft/vscode-mock-debug#43]
Proposed improvements to the features recently added in support of https://github.com/microsoft/vscode/issues/92269

- Prefix the commands with `Mock Debug: `
- Hide the commands from the Command Palette
- Disable the commands when in debug mode, otherwise the editor command buttons remain active and could be mistaken for ways to interact with the debugging just launched. If they remain active and are clicked the user ends up with multiple concurrent debug sessions, which could be another source of confusion.

I will submit a PR shortly.

**Comment by gjsjohnmurray** [comment]
@isidorn @weinand my PR #44 is ready for review. Its purpose is to make Mock Debug an even better model for the recommendations stated at https://github.com/microsoft/vscode/issues/92269#issuecomment-650034660. In particular it uses enablement to deactivate the command buttons when debug is in progress. See above for my reasoning.

**Comment by isidorn** [comment]
@gjsjohnmurray thanks a lot for looking into this! I will comment in the PR

**Comment by weinand** [comment]
I've merged the PR
