### ISSUE TITLE
Create forum for asking questions and link to it in the readme.md

### ISSUE THREAD

**Issue by indiejames** [Microsoft/vscode-mock-debug#5]
It would be very helpful to have a forum for asking questions about building debuggers based on mock debug. Please create one and add a link to it in the readme.md. If such a forum already exists I cannot find it anywhere on the vscode portal or github page.

Thanks,

James

**Comment by weinand** [comment]
@indiejames Please ask questions about debug adapters on https://gitter.im/Microsoft/vscode
