### ISSUE TITLE
Running mock debugger gives error during activation

### ISSUE THREAD

**Issue by jscheeres** [microsoft/vscode-mock-debug#51]
Os: Windows 10
NodeJs version: 14.6

Reproduction steps:

1. Start extension
2. Open test.md in extension development host
3. Debug the markdown file (hit F5)
4. Error

![image](https://user-images.githubusercontent.com/10026982/110751650-73602580-8244-11eb-9594-e9b65dad4155.png)

Error message:
Activating extension 'andreweinand.mock-debug' failed: a DebugAdapterDescriptorFactory can only be registered from the extension that defines the 'mock' debugger..

I also tested it on Ubuntu with NodeJs 14.13.1. It works on Ubuntu.

**Comment by weinand** [comment]
This is VS Code problem https://github.com/microsoft/vscode/issues/118562 which is fixed in VS Code 1.54.3.
