### ISSUE TITLE
Cannot run through tutorial with latest stable release of 1.62.3

### ISSUE THREAD

**Issue by leoyulee** [microsoft/vscode-mock-debug#64]
I recently tried to go through the tutorial at https://code.visualstudio.com/api/extension-guides/debugger-extension, but found out that the extension could not be debugged on my client without adjusting the version back to 1.62.3. I'm not sure if this was intentional.
https://github.com/microsoft/vscode-mock-debug/blob/2efdfbbcf8deffd1e16e4a043c920fda9c466dc6/package.json#L16

**Comment by weinand** [comment]
Yes, Mock Debug requires the latest version of VS Code (stable) because it showcases new debug features of VS Code.
