### ISSUE TITLE
can this extension run on https://vscode.dev/

### ISSUE THREAD

**Issue by zhfnjust** [microsoft/vscode-mock-debug#68]

**Comment by zhfnjust** [comment]
When I start the debugger, it doesn't respond
<img width="2094" alt="image" src="https://user-images.githubusercontent.com/995909/173329003-47eb8f64-576d-4a04-afd5-016715a44d29.png">

**Comment by Trass3r** [comment]
Same here. If you open the devtools:
```js
Uncaught (in promise) ReferenceError: process is not defined
	at et.normalizePathAndCasing (web-extension.js:10:19521)
	at et.start (web-extension.js:10:13434)
	at G.launchRequest (web-extension.js:12:2034)
```
https://github.com/microsoft/vscode-mock-debug/blob/72b556cd0cfe0b162333cf9c7c5c341744914ad8/src/mockRuntime.ts#L677

**Comment by weinand** [comment]
This was broken by commit 72b556cd0cfe0b162333cf9c7c5c341744914ad8:
`process` is node API which does not exist when running in the browser.

/cc @connor4312

**Comment by billti** [comment]
p.s. Let me know if I should open a new issue @weinand rather than just pile on here. Thanks!
