### ISSUE TITLE
Is there public specification of cdp?

### ISSUE THREAD

**Issue by mkwork** [Microsoft/vscode-mock-debug#9]
Just like [lsp](https://github.com/Microsoft/language-server-protocol).

**Comment by weinand** [comment]
The abbreviation for **VS Code Debugger Protocol** is "VSDP". 
(CDP is the "Chrome debugger protocol" which is a different thing as VSDP).

Everything related to VSDP lives in this github repository: https://github.com/Microsoft/vscode-debugadapter-node

A json schema for VSDP is here: https://github.com/Microsoft/vscode-debugadapter-node/blob/master/debugProtocol.json
A [generator program](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/src/generator.ts) converts the schema into [TypeScript](https://github.com/Microsoft/vscode-debugadapter-node/blob/master/protocol/src/debugProtocol.ts).
