### ISSUE TITLE
Remove onCommand:extension.mock-debug.getProgramName activation event?

### ISSUE THREAD

**Issue by MortimerSC** [microsoft/vscode-mock-debug#95]
You can't remove this one?

_Originally posted by @Tyriar in https://github.com/microsoft/vscode-mock-debug/pull/90#discussion_r1093686230_

**Comment by connor4312** [comment]
No, but there are some extra commands that we can remove

**Comment by connor4312** [comment]
No, since that's not a registered "public" command
